[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  '@/src=src',
  '@/script=script',
  '@/tests=tests',
  # '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/'
]

# See more config options githubhttps://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
